### ISSUE TITLE
Failed to compile: unable to load front end 

### ISSUE THREAD

**Issue by arquimed** [aragon/aragon-cli#180]
Hi all! 

I am working on ubuntu 16.04 LTS, with Nodejs v.10.9.0 installed. I have followed all the steps on the tutorial correctly and deployed a test dapp:

1) npm i -g @aragon/cli
2) aragon init [name of dapp].aragonpm.eth react
3) npm i parcel-bundler -D
4) npm run build
5) npm run

The process runs smoothly and a new tab is opened on Firefox at http://localhost:3000/#/0xcb665437f03f2845D029619D539BEf9B4FDeFBA6.

However, I get the following screen:

![failed to compile](https://user-images.githubusercontent.com/40397040/44627154-28ea5800-a929-11e8-8084-e6dffc21180e.png)

"This error occurred during the build time and cannot be dismissed."

The error message from the console is:
Warning: The "extend" API will be removed in the upcoming v4.0 release. Use styled(StyledComponent) instead. You can find more information here: https://github.com/styled-components/styled-components/issues/1546 styled-components.browser.esm.js:1696
[Show/hide message details.] Error: Cannot find module "@babel/runtime/helpers/esm/extends" web.js:1
./node_modules/react-spring/dist/web.js
Module not found: Can't resolve '@babel/runtime/helpers/esm/extends' in '/home/democritus/.aragon/wrapper-e60e74107c1d63a34010869159d945f919443851/node_modules/react-spring/dist' index.js:2284
./node_modules/react-spring/dist/web.js
Module not found: Can't resolve '@babel/runtime/helpers/esm/inheritsLoose' in '/home/democritus/.aragon/wrapper-e60e74107c1d63a34010869159d945f919443851/node_modules/react-spring/dist' index.js:2284
./node_modules/react-spring/dist/web.js
Module not found: Can't resolve '@babel/runtime/helpers/esm/objectWithoutPropertiesLoose' in '/home/democritus/.aragon/wrapper-e60e74107c1d63a34010869159d945f919443851/node_modules/react-spring/dist'

![console-error](https://user-images.githubusercontent.com/40397040/44627173-81215a00-a929-11e8-8439-d16bc2372b86.png)

I've been stuck at this point for a while, any help would be greatly appreciated.
This problem persists even if I install bare template.
Thanks in advanced!

**Comment by sohkai** [comment]
@arquimed Ahh, seems like this is a problem with [aragon/aragon](http://github.com/aragon/aragon).

Do you mind cloning that repo and trying to spin it up (`npm install` and `npm start`)?

**Comment by arquimed** [comment]
Hi there @sohkai !

After opening a new dir and doing the following steps:

- git clone https://github.com/aragon/aragon

- npm install

- npm start

I get the same error on compilation:

![aragon-aragon](https://user-images.githubusercontent.com/40397040/44628062-871f3700-a939-11e8-8bca-36165cb523ee.png)

I wonder whether it is the first time you get to know this issue? Should I reinstall npm or use a different version? Or yarn?

Sorry to bother!

**Comment by arquimed** [comment]
Hi there @izqui !

I erased the project folder and proceeded to re-do the steps shown in my previous message (cloning aragon-aragon repo, etc), but I do still get the same error message.

![screenshot from 2018-08-27 18-05-37](https://user-images.githubusercontent.com/40397040/44670760-db064a80-aa23-11e8-96c7-c4c6f7b9905d.png)

Would you be so kind to describe step by step the steps I should do in order to be sure that I am following the right instructions? Considering starting from scratch. I've been trying to follow the instructions of your tutorial so far, but without success.

Thanks!

**Comment by izqui** [comment]
Did you update to update the CLI to v4.1.6? You can check your version doing `aragon --version`.

If you are still in the previous version, you can update by doing:

```npm install -g @aragon/cli```

There is actually no need for you to clone the aragon/aragon repo, just need to update to the latest version of the CLI.

**Comment by izqui** [comment]
Oh I think you may be trying to be starting aragon/aragon rather than your app using the CLI. Go to your Aragon app directory and do `aragon run`.

**Comment by arquimed** [comment]
Awesome!! After creating a totally new project and following the steps as described in tutorial I have been able to set my first test DAO using Aragon-cli.

Feels AMAZING xD

Thanks for the help!

![aragon-cli](https://user-images.githubusercontent.com/40397040/44743583-2d6a6880-ab03-11e8-8336-4d99f1969445.png)
